/* ==========================================================================
   MCU-DATA.JS
   Master dataset for every project in the Marvel Cinematic Universe tracker.
   Poster art is generated procedurally (see generatePoster in script.js) so
   the app never depends on external image hosts and works fully offline.
   ========================================================================== */

const MCU_TYPES = {
  MOVIE: "Movie",
  DISNEY: "Disney+ Series",
  NETFLIX: "Netflix Series",
  SPECIAL: "Special",
  ONESHOT: "One-Shot",
  ANIMATED: "Animated",
  UPCOMING: "Upcoming"
};

const MCU_DATA = [
  // ---------------------------- PHASE ONE ----------------------------
  { id: "iron-man", title: "Iron Man", type: MCU_TYPES.MOVIE, phase: "Phase 1", saga: "Infinity Saga",
    releaseDate: "2008-05-02", chronOrder: 5, runtime: 126,
    description: "A billionaire industrialist builds a suit of armor to escape captivity and becomes Earth's first mechanized hero.",
    watched: false, favorite: false },
  { id: "incredible-hulk", title: "The Incredible Hulk", type: MCU_TYPES.MOVIE, phase: "Phase 1", saga: "Infinity Saga",
    releaseDate: "2008-06-13", chronOrder: 6, runtime: 112,
    description: "A gamma-radiation experiment gone wrong forces a scientist on the run from the military and his own rage.",
    watched: false, favorite: false },
  { id: "iron-man-2", title: "Iron Man 2", type: MCU_TYPES.MOVIE, phase: "Phase 1", saga: "Infinity Saga",
    releaseDate: "2010-05-07", chronOrder: 7, runtime: 124,
    description: "Fame and a failing power source push a hero to his limits as new rivals emerge at home and abroad.",
    watched: false, favorite: false },
  { id: "consultant", title: "The Consultant", type: MCU_TYPES.ONESHOT, phase: "Phase 1", saga: "Infinity Saga",
    releaseDate: "2011-09-13", chronOrder: 8, runtime: 4,
    description: "A short comic interlude reveals the bureaucratic strings pulled behind a major roster decision.",
    watched: false, favorite: false },
  { id: "thor", title: "Thor", type: MCU_TYPES.MOVIE, phase: "Phase 1", saga: "Infinity Saga",
    releaseDate: "2011-05-06", chronOrder: 1, runtime: 115,
    description: "An arrogant god is cast down to Earth and must learn humility before he can reclaim his hammer.",
    watched: false, favorite: false },
  { id: "funny-thing", title: "A Funny Thing Happened on the Way to Thor's Hammer", type: MCU_TYPES.ONESHOT, phase: "Phase 1", saga: "Infinity Saga",
    releaseDate: "2011-10-25", chronOrder: 2, runtime: 4,
    description: "A government agent's night shift turns absurd when a certain enchanted hammer needs watching.",
    watched: false, favorite: false },
  { id: "cap-first-avenger", title: "Captain America: The First Avenger", type: MCU_TYPES.MOVIE, phase: "Phase 1", saga: "Infinity Saga",
    releaseDate: "2011-07-22", chronOrder: 3, runtime: 124,
    description: "A frail volunteer becomes a super-soldier and leads the fight against a rogue Nazi science division.",
    watched: false, favorite: false },
  { id: "item-47", title: "Item 47", type: MCU_TYPES.ONESHOT, phase: "Phase 1", saga: "Infinity Saga",
    releaseDate: "2012-09-25", chronOrder: 10, runtime: 12,
    description: "A young couple finds an alien weapon left behind after a citywide battle and puts it to dangerous use.",
    watched: false, favorite: false },
  { id: "avengers", title: "The Avengers", type: MCU_TYPES.MOVIE, phase: "Phase 1", saga: "Infinity Saga",
    releaseDate: "2012-05-04", chronOrder: 9, runtime: 143,
    description: "Earth's mightiest heroes assemble for the first time to stop an Asgardian invasion of New York.",
    watched: false, favorite: false },

  // ---------------------------- PHASE TWO ----------------------------
  { id: "iron-man-3", title: "Iron Man 3", type: MCU_TYPES.MOVIE, phase: "Phase 2", saga: "Infinity Saga",
    releaseDate: "2013-05-03", chronOrder: 12, runtime: 130,
    description: "Shaken by New York, a hero rebuilds himself from nothing while a shadowy terrorist targets his home.",
    watched: false, favorite: false },
  { id: "agent-carter-oneshot", title: "Agent Carter", type: MCU_TYPES.ONESHOT, phase: "Phase 2", saga: "Infinity Saga",
    releaseDate: "2013-09-06", chronOrder: 4, runtime: 15,
    description: "Years after the war, a decorated agent is relegated to desk work until one night proves otherwise.",
    watched: false, favorite: false },
  { id: "thor-dark-world", title: "Thor: The Dark World", type: MCU_TYPES.MOVIE, phase: "Phase 2", saga: "Infinity Saga",
    releaseDate: "2013-11-08", chronOrder: 13, runtime: 112,
    description: "An ancient race of dark elves resurfaces to plunge the universe into darkness using a hidden weapon.",
    watched: false, favorite: false },
  { id: "all-hail-king", title: "All Hail the King", type: MCU_TYPES.ONESHOT, phase: "Phase 2", saga: "Infinity Saga",
    releaseDate: "2014-09-05", chronOrder: 16, runtime: 15,
    description: "A documentary crew visits a supposed terrorist mastermind in prison, unraveling a stranger truth.",
    watched: false, favorite: false },
  { id: "cap-winter-soldier", title: "Captain America: The Winter Soldier", type: MCU_TYPES.MOVIE, phase: "Phase 2", saga: "Infinity Saga",
    releaseDate: "2014-04-04", chronOrder: 14, runtime: 136,
    description: "A soldier out of time uncovers a conspiracy that has been rotting a spy agency from within.",
    watched: false, favorite: false },
  { id: "guardians-galaxy", title: "Guardians of the Galaxy", type: MCU_TYPES.MOVIE, phase: "Phase 2", saga: "Infinity Saga",
    releaseDate: "2014-08-01", chronOrder: 11, runtime: 121,
    description: "A ragtag crew of misfits bands together to stop a fanatic from acquiring a planet-destroying orb.",
    watched: false, favorite: false },
  { id: "avengers-ultron", title: "Avengers: Age of Ultron", type: MCU_TYPES.MOVIE, phase: "Phase 2", saga: "Infinity Saga",
    releaseDate: "2015-05-01", chronOrder: 15, runtime: 141,
    description: "An artificial intelligence built to protect the world instead decides humanity itself is the threat.",
    watched: false, favorite: false },
  { id: "ant-man", title: "Ant-Man", type: MCU_TYPES.MOVIE, phase: "Phase 2", saga: "Infinity Saga",
    releaseDate: "2015-07-17", chronOrder: 17, runtime: 117,
    description: "A reformed thief dons a size-shifting suit to pull off an impossible heist for the greater good.",
    watched: false, favorite: false },

  // -------------------- NETFLIX / DEFENDERS SAGA --------------------
  { id: "daredevil-s1", title: "Daredevil (Season 1)", type: MCU_TYPES.NETFLIX, phase: "Phase 2", saga: "Infinity Saga",
    releaseDate: "2015-04-10", chronOrder: 18, runtime: 572,
    description: "A blind lawyer by day becomes a masked vigilante by night, taking on Hell's Kitchen's crime lords.",
    watched: false, favorite: false },
  { id: "jessica-jones-s1", title: "Jessica Jones (Season 1)", type: MCU_TYPES.NETFLIX, phase: "Phase 2", saga: "Infinity Saga",
    releaseDate: "2015-11-20", chronOrder: 19, runtime: 611,
    description: "A hard-drinking private investigator with super strength is drawn back into a fight with her abuser.",
    watched: false, favorite: false },
  { id: "daredevil-s2", title: "Daredevil (Season 2)", type: MCU_TYPES.NETFLIX, phase: "Phase 2", saga: "Infinity Saga",
    releaseDate: "2016-03-18", chronOrder: 20, runtime: 655,
    description: "A vigilante is pushed to his limits by a gun-toting punisher and the return of an old flame.",
    watched: false, favorite: false },
  { id: "luke-cage-s1", title: "Luke Cage (Season 1)", type: MCU_TYPES.NETFLIX, phase: "Phase 2", saga: "Infinity Saga",
    releaseDate: "2016-09-30", chronOrder: 21, runtime: 655,
    description: "A man with unbreakable skin becomes the reluctant protector of his Harlem neighborhood.",
    watched: false, favorite: false },
  { id: "iron-fist-s1", title: "Iron Fist (Season 1)", type: MCU_TYPES.NETFLIX, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2017-03-17", chronOrder: 22, runtime: 655,
    description: "A presumed-dead heir returns home wielding a mystical martial art and a score to settle.",
    watched: false, favorite: false },
  { id: "defenders", title: "The Defenders", type: MCU_TYPES.NETFLIX, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2017-08-18", chronOrder: 23, runtime: 372,
    description: "Four street-level heroes reluctantly team up to stop an ancient organization from destroying the city.",
    watched: false, favorite: false },
  { id: "punisher-s1", title: "The Punisher (Season 1)", type: MCU_TYPES.NETFLIX, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2017-11-17", chronOrder: 24, runtime: 655,
    description: "A grieving veteran wages a one-man war against the criminal network that took his family.",
    watched: false, favorite: false },
  { id: "jessica-jones-s2", title: "Jessica Jones (Season 2)", type: MCU_TYPES.NETFLIX, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2018-03-08", chronOrder: 25, runtime: 611,
    description: "Digging into the origin of her powers forces a detective to confront the source of her trauma.",
    watched: false, favorite: false },
  { id: "luke-cage-s2", title: "Luke Cage (Season 2)", type: MCU_TYPES.NETFLIX, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2018-06-22", chronOrder: 26, runtime: 655,
    description: "A returning rival forces Harlem's protector to question how far he'll go to keep the peace.",
    watched: false, favorite: false },
  { id: "iron-fist-s2", title: "Iron Fist (Season 2)", type: MCU_TYPES.NETFLIX, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2018-09-07", chronOrder: 27, runtime: 502,
    description: "The Iron Fist must defend his city while an old friend circles closer to his mystical power.",
    watched: false, favorite: false },
  { id: "daredevil-s3", title: "Daredevil (Season 3)", type: MCU_TYPES.NETFLIX, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2018-10-19", chronOrder: 28, runtime: 655,
    description: "Broken in body and faith, a vigilante returns to face his oldest enemy from a prison cell outward.",
    watched: false, favorite: false },
  { id: "punisher-s2", title: "The Punisher (Season 2)", type: MCU_TYPES.NETFLIX, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2019-01-18", chronOrder: 29, runtime: 611,
    description: "A former soldier trying to leave his war behind is pulled back in to protect someone he cannot save alone.",
    watched: false, favorite: false },
  { id: "jessica-jones-s3", title: "Jessica Jones (Season 3)", type: MCU_TYPES.NETFLIX, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2019-06-14", chronOrder: 30, runtime: 611,
    description: "A methodical new adversary forces a jaded hero to decide what kind of protector she wants to be.",
    watched: false, favorite: false },

  // ---------------------------- PHASE THREE ----------------------------
  { id: "cap-civil-war", title: "Captain America: Civil War", type: MCU_TYPES.MOVIE, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2016-05-06", chronOrder: 31, runtime: 147,
    description: "Government oversight splits Earth's heroes into two camps that collide over a fractured friendship.",
    watched: false, favorite: false },
  { id: "doctor-strange", title: "Doctor Strange", type: MCU_TYPES.MOVIE, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2016-11-04", chronOrder: 32, runtime: 115,
    description: "A brilliant but arrogant surgeon loses everything and finds a new purpose in the mystic arts.",
    watched: false, favorite: false },
  { id: "guardians-2", title: "Guardians of the Galaxy Vol. 2", type: MCU_TYPES.MOVIE, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2017-05-05", chronOrder: 33, runtime: 137,
    description: "The Guardians confront a cosmic father figure whose gifts hide a devastating price.",
    watched: false, favorite: false },
  { id: "spiderman-homecoming", title: "Spider-Man: Homecoming", type: MCU_TYPES.MOVIE, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2017-07-07", chronOrder: 34, runtime: 133,
    description: "A teenage hero balances high school life with proving himself worthy of joining the big leagues.",
    watched: false, favorite: false },
  { id: "thor-ragnarok", title: "Thor: Ragnarok", type: MCU_TYPES.MOVIE, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2017-11-03", chronOrder: 35, runtime: 130,
    description: "Stripped of his hammer and exiled to a gladiator planet, a god must race home before it's destroyed.",
    watched: false, favorite: false },
  { id: "black-panther", title: "Black Panther", type: MCU_TYPES.MOVIE, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2018-02-16", chronOrder: 36, runtime: 134,
    description: "A new king must defend his hidden, technologically advanced homeland from a vengeful challenger.",
    watched: false, favorite: false },
  { id: "avengers-infinity-war", title: "Avengers: Infinity War", type: MCU_TYPES.MOVIE, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2018-04-27", chronOrder: 37, runtime: 149,
    description: "Every hero in the galaxy converges to stop a mad titan from collecting all six stones of power.",
    watched: false, favorite: false },
  { id: "ant-man-wasp", title: "Ant-Man and the Wasp", type: MCU_TYPES.MOVIE, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2018-07-06", chronOrder: 38, runtime: 118,
    description: "A shrinking hero teams with a new partner on a rescue mission into a strange subatomic realm.",
    watched: false, favorite: false },
  { id: "captain-marvel", title: "Captain Marvel", type: MCU_TYPES.MOVIE, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2019-03-08", chronOrder: 0, runtime: 123,
    description: "A fighter pilot turned cosmic warrior uncovers buried memories that connect her to two warring alien races.",
    watched: false, favorite: false },
  { id: "avengers-endgame", title: "Avengers: Endgame", type: MCU_TYPES.MOVIE, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2019-04-26", chronOrder: 39, runtime: 181,
    description: "The remaining Avengers attempt one last time heist to undo a universe-shattering act of genocide.",
    watched: false, favorite: false },
  { id: "spiderman-far-from-home", title: "Spider-Man: Far From Home", type: MCU_TYPES.MOVIE, phase: "Phase 3", saga: "Infinity Saga",
    releaseDate: "2019-07-02", chronOrder: 40, runtime: 129,
    description: "On a school trip across Europe, a young hero is recruited to face elemental threats and a mysterious ally.",
    watched: false, favorite: false },

  // ---------------------------- PHASE FOUR ----------------------------
  { id: "black-widow", title: "Black Widow", type: MCU_TYPES.MOVIE, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2021-07-09", chronOrder: 41, runtime: 134,
    description: "A former spy confronts her family of assassins and the shadow program that made her.",
    watched: false, favorite: false },
  { id: "wandavision", title: "WandaVision", type: MCU_TYPES.DISNEY, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2021-01-15", chronOrder: 42, runtime: 340,
    description: "A grieving witch builds an idyllic sitcom life for herself and her love in a suburb that hides a dark secret.",
    watched: false, favorite: false },
  { id: "falcon-winter-soldier", title: "The Falcon and the Winter Soldier", type: MCU_TYPES.DISNEY, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2021-03-19", chronOrder: 43, runtime: 290,
    description: "Two allies grapple with a legendary shield's legacy while a new super soldier program spirals out of control.",
    watched: false, favorite: false },
  { id: "loki-s1", title: "Loki (Season 1)", type: MCU_TYPES.DISNEY, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2021-06-09", chronOrder: 44, runtime: 290,
    description: "Pulled from the timeline for his crimes, a trickster god is recruited to hunt a variant of himself.",
    watched: false, favorite: false },
  { id: "shang-chi", title: "Shang-Chi and the Legend of the Ten Rings", type: MCU_TYPES.MOVIE, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2021-09-03", chronOrder: 45, runtime: 132,
    description: "A man confronts the martial arts legacy and criminal empire of the father he left behind.",
    watched: false, favorite: false },
  { id: "what-if-s1", title: "What If...? (Season 1)", type: MCU_TYPES.ANIMATED, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2021-08-11", chronOrder: 46, runtime: 240,
    description: "A cosmic watcher narrates alternate timelines where a single choice reshapes the entire universe.",
    watched: false, favorite: false },
  { id: "eternals", title: "Eternals", type: MCU_TYPES.MOVIE, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2021-11-05", chronOrder: 47, runtime: 156,
    description: "An ancient order of immortal guardians reunites after millennia to face a threat born from their own creation.",
    watched: false, favorite: false },
  { id: "hawkeye", title: "Hawkeye", type: MCU_TYPES.DISNEY, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2021-11-24", chronOrder: 48, runtime: 290,
    description: "A retired archer trains a driven young protege while a debt from his past comes due at Christmas.",
    watched: false, favorite: false },
  { id: "spiderman-no-way-home", title: "Spider-Man: No Way Home", type: MCU_TYPES.MOVIE, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2021-12-17", chronOrder: 49, runtime: 148,
    description: "A spell to hide a hero's identity rips open the multiverse and invites in dangerous familiar faces.",
    watched: false, favorite: false },
  { id: "moon-knight", title: "Moon Knight", type: MCU_TYPES.DISNEY, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2022-03-30", chronOrder: 50, runtime: 290,
    description: "A mild-mannered gift shop worker discovers he shares a body and an Egyptian god with a mercenary alter ego.",
    watched: false, favorite: false },
  { id: "doctor-strange-multiverse", title: "Doctor Strange in the Multiverse of Madness", type: MCU_TYPES.MOVIE, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2022-05-06", chronOrder: 51, runtime: 126,
    description: "A sorcerer ventures into terrifying alternate realities to protect a girl who can travel between them.",
    watched: false, favorite: false },
  { id: "ms-marvel", title: "Ms. Marvel", type: MCU_TYPES.DISNEY, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2022-06-08", chronOrder: 52, runtime: 290,
    description: "A New Jersey teenager obsessed with superheroes discovers she has cosmic powers of her own.",
    watched: false, favorite: false },
  { id: "thor-love-thunder", title: "Thor: Love and Thunder", type: MCU_TYPES.MOVIE, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2022-07-08", chronOrder: 53, runtime: 119,
    description: "A god searching for peace is drawn back into battle by a former love and a killer hunting deities.",
    watched: false, favorite: false },
  { id: "i-am-groot", title: "I Am Groot", type: MCU_TYPES.ANIMATED, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2022-08-10", chronOrder: 54, runtime: 45,
    description: "A collection of shorts follows a mischievous sapling getting into trouble across the cosmos.",
    watched: false, favorite: false },
  { id: "she-hulk", title: "She-Hulk: Attorney at Law", type: MCU_TYPES.DISNEY, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2022-08-18", chronOrder: 55, runtime: 240,
    description: "A lawyer inherits her cousin's gamma-powered strength and tries to keep a normal life anyway.",
    watched: false, favorite: false },
  { id: "werewolf-by-night", title: "Werewolf by Night", type: MCU_TYPES.SPECIAL, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2022-10-07", chronOrder: 56, runtime: 55,
    description: "A gathering of monster hunters competing for a relic turns into a gothic showdown at a secluded mansion.",
    watched: false, favorite: false },
  { id: "black-panther-wakanda-forever", title: "Black Panther: Wakanda Forever", type: MCU_TYPES.MOVIE, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2022-11-11", chronOrder: 57, runtime: 161,
    description: "A nation in mourning must find a new protector while a hidden undersea kingdom declares war.",
    watched: false, favorite: false },
  { id: "guardians-holiday-special", title: "The Guardians of the Galaxy Holiday Special", type: MCU_TYPES.SPECIAL, phase: "Phase 4", saga: "Multiverse Saga",
    releaseDate: "2022-11-25", chronOrder: 58, runtime: 44,
    description: "Two Guardians set off to Earth on a chaotic mission to deliver the perfect holiday gift for their captain.",
    watched: false, favorite: false },

  // ---------------------------- PHASE FIVE ----------------------------
  { id: "ant-man-quantumania", title: "Ant-Man and the Wasp: Quantumania", type: MCU_TYPES.MOVIE, phase: "Phase 5", saga: "Multiverse Saga",
    releaseDate: "2023-02-17", chronOrder: 59, runtime: 125,
    description: "A family is pulled into the Quantum Realm and comes face to face with a conqueror who rules it.",
    watched: false, favorite: false },
  { id: "secret-invasion", title: "Secret Invasion", type: MCU_TYPES.DISNEY, phase: "Phase 5", saga: "Multiverse Saga",
    releaseDate: "2023-06-21", chronOrder: 60, runtime: 240,
    description: "A veteran spy races to stop a faction of shapeshifters from quietly replacing world leaders.",
    watched: false, favorite: false },
  { id: "guardians-3", title: "Guardians of the Galaxy Vol. 3", type: MCU_TYPES.MOVIE, phase: "Phase 5", saga: "Multiverse Saga",
    releaseDate: "2023-05-05", chronOrder: 61, runtime: 150,
    description: "The team risks everything on a mission to save one of their own from the scientist who created him.",
    watched: false, favorite: false },
  { id: "what-if-s2", title: "What If...? (Season 2)", type: MCU_TYPES.ANIMATED, phase: "Phase 5", saga: "Multiverse Saga",
    releaseDate: "2023-12-22", chronOrder: 62, runtime: 216,
    description: "More cosmic detours explore timelines where familiar heroes make very different choices.",
    watched: false, favorite: false },
  { id: "loki-s2", title: "Loki (Season 2)", type: MCU_TYPES.DISNEY, phase: "Phase 5", saga: "Multiverse Saga",
    releaseDate: "2023-10-05", chronOrder: 63, runtime: 290,
    description: "A fracturing timeline sends a reformed trickster scrambling to hold the multiverse together.",
    watched: false, favorite: false },
  { id: "the-marvels", title: "The Marvels", type: MCU_TYPES.MOVIE, phase: "Phase 5", saga: "Multiverse Saga",
    releaseDate: "2023-11-10", chronOrder: 64, runtime: 105,
    description: "Three heroes with entangled powers must work together after their abilities start swapping their locations.",
    watched: false, favorite: false },
  { id: "echo", title: "Echo", type: MCU_TYPES.DISNEY, phase: "Phase 5", saga: "Multiverse Saga",
    releaseDate: "2024-01-09", chronOrder: 65, runtime: 240,
    description: "A deaf, disgraced protege returns to her hometown roots to confront her family's criminal past.",
    watched: false, favorite: false },
  { id: "agatha-all-along", title: "Agatha All Along", type: MCU_TYPES.DISNEY, phase: "Phase 5", saga: "Multiverse Saga",
    releaseDate: "2024-09-18", chronOrder: 66, runtime: 290,
    description: "A powerless witch assembles a coven to walk a deadly road that promises to restore what she lost.",
    watched: false, favorite: false },
  { id: "deadpool-wolverine", title: "Deadpool & Wolverine", type: MCU_TYPES.MOVIE, phase: "Phase 5", saga: "Multiverse Saga",
    releaseDate: "2024-07-26", chronOrder: 67, runtime: 128,
    description: "A washed-up mercenary drags a reluctant, clawed variant into a fight to save his own crumbling reality.",
    watched: false, favorite: false },
  { id: "captain-america-brave-new-world", title: "Captain America: Brave New World", type: MCU_TYPES.MOVIE, phase: "Phase 5", saga: "Multiverse Saga",
    releaseDate: "2025-02-14", chronOrder: 68, runtime: 118,
    description: "The new shield-bearer is thrust into an international incident tied to a mysterious new element.",
    watched: false, favorite: false },
  { id: "thunderbolts", title: "Thunderbolts*", type: MCU_TYPES.MOVIE, phase: "Phase 5", saga: "Multiverse Saga",
    releaseDate: "2025-05-02", chronOrder: 69, runtime: 127,
    description: "A crew of morally gray operatives are thrown together on a mission that may make them something more.",
    watched: false, favorite: false },
  { id: "ironheart", title: "Ironheart", type: MCU_TYPES.DISNEY, phase: "Phase 5", saga: "Multiverse Saga",
    releaseDate: "2025-06-24", chronOrder: 70, runtime: 240,
    description: "A brilliant young inventor builds her own suit of armor and gets pulled toward a dangerous shortcut.",
    watched: false, favorite: false },
  { id: "fantastic-four-first-steps", title: "The Fantastic Four: First Steps", type: MCU_TYPES.MOVIE, phase: "Phase 6", saga: "Multiverse Saga",
    releaseDate: "2025-07-25", chronOrder: 71, runtime: 115,
    description: "A family of retro-futuristic explorers gains cosmic powers and must defend their world from a planetary threat.",
    watched: false, favorite: false },

  // ---------------------------- UPCOMING ----------------------------
  { id: "wonder-man", title: "Wonder Man", type: MCU_TYPES.UPCOMING, phase: "Phase 6", saga: "Multiverse Saga",
    releaseDate: "2026-01-01", chronOrder: 72, runtime: null,
    description: "A stunt double turned reluctant hero navigates Hollywood, family legacy, and his own growing powers.",
    watched: false, favorite: false },
  { id: "spiderman-brand-new-day", title: "Spider-Man: Brand New Day", type: MCU_TYPES.UPCOMING, phase: "Phase 6", saga: "Multiverse Saga",
    releaseDate: "2026-07-31", chronOrder: 73, runtime: null,
    description: "A fresh chapter for the wall-crawler as he tries to rebuild a normal life the world keeps interrupting.",
    watched: false, favorite: false },
  { id: "avengers-doomsday", title: "Avengers: Doomsday", type: MCU_TYPES.UPCOMING, phase: "Phase 6", saga: "Multiverse Saga",
    releaseDate: "2026-12-18", chronOrder: 74, runtime: null,
    description: "A sprawling roster of heroes and variants converges to face a threat that spans timelines.",
    watched: false, favorite: false },
  { id: "avengers-secret-wars", title: "Avengers: Secret Wars", type: MCU_TYPES.UPCOMING, phase: "Phase 6", saga: "Multiverse Saga",
    releaseDate: "2027-12-17", chronOrder: 75, runtime: null,
    description: "The Multiverse Saga reaches its finale as realities collide and heroes make their last stand.",
    watched: false, favorite: false }
];

// Freeze base records so accidental mutation of the source array is impossible;
// the app clones entries into working state instead.
Object.freeze(MCU_DATA);
